filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: {  }

tools:
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: "PSR2"

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
