filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
tools:
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: "PSR2"